### ISSUE TITLE
The basic demo doesn't work.

### ISSUE THREAD

**Issue by szhu** [evanw/node-source-map-support#127]
I'm following the basic demo here:
https://github.com/evanw/node-source-map-support#basic-demo

``` fish
npm install source-map-support

echo 'throw new Error("test"); // This is the original code' > original.js

echo 'require("source-map-support").install();

throw new Error("test"); // This is the compiled code
// The next line defines the sourceMapping.
//# sourceMappingURL=compiled.js.map' > compiled.js

echo '{
  "version": 3,
  "file": "compiled.js",
  "sources": ["original.js"],
  "names": [],
  "mappings": ";;;AAAA,MAAM,IAAI"
}' > compiled.js.map

node compiled.js
```

And I get:

```
.../compiled.js:3
throw new Error(test); // This is the compiled code
      ^
Error: test
```

**Comment by szhu** [comment]
Oh there's also #97

**Comment by jeremytm** [comment]
Same here. Is this project still active??

**Comment by jeremytm** [comment]
After looking around, I see that node removed the call to `prepareStackTrace` which this module relies on... So the obvious question is: **if it doesn't work anymore, why does this module still exist?**

**Comment by uiteoi** [comment]
There is an error in documented *compiled.js.map*, an extra semi-column at the start of "mappings", try this instead and it will work:
```
echo '{
  "version": 3,
  "file": "compiled.js",
  "sources": ["original.js"],
  "names": [],
  "mappings": ";;AAAA,MAAM,IAAI"
}' > compiled.js.map
```

**Comment by LinusU** [comment]
Fixed in 0.4.15

**Comment by uiteoi** [comment]
You might also want to close issue #97 which seems to describe the same issue.

**Comment by jeremytm** [comment]
Thanks team. I've got things working.

Part of the reason I thought this was broken and tried the demo is because I couldn't get it to work in my own project.

The problem turned out to be this line from your README:
> Once you have a valid source map, insert the following line at the top of your compiled code:
> ```
> require('source-map-support').install();
> ```

I was inserting this line at the top of an already **compiled file** (as the instructions said) and then expecting it to work. But my sourcemaps are generated by babel at the same time as compilation, so with an extra line added _after_ the sourcemap had been generated, things got messed up.

The fix ended up being to insert this line in the **original file** before compilation, and then everything worked.

I'm happy to submit a PR request for the README, but could someone confirm that how I'm doing things is correct?

**Comment by uiteoi** [comment]
@jeremytm, The error in README/basic demo was an extra semi-column at the start of "mappings". It is now fixed.

For Babel, you indeed need to include ```require('source-map-support').install();``` in the source file otherwise mappings would be wrong. There are examples in README for TypeScript and CoffeeScript which should be similar to what could be done with Babel.

There is also another option for Babel mentioned in README:
**"Note: if you're using babel-register, it includes source-map-support already."**
