### ISSUE TITLE
Discards AWS Lambda initialization error message and stack trace.

### ISSUE THREAD

**Issue by catamphetamine** [evanw/node-source-map-support#240]
I have been debugging a strange uninformative error `module initialization error: Error` on AWS Lambda at lambda initialization time.
Turned out that as soon as I comment out `import 'source-map-support/register'` the error starts showing the actual error message and stack trace.

**Comment by vitush93** [comment]
`Error.prepareStackTrace` replacement is what breaks aws lambda's error-extraction mechanism. 

This only occurs for errors outside the lambda handler (presumably inside imported dependencies). In order to get error info (although without source map support), make sure the `register` is imported last.

Or manually import the `install` function and call it just before your function handler (=after all imports). Alternatively call `install()` inside the function handler.

Note that source-map-support may touch the filesystem on each invocation if the `install()` call is inside the handler, adding overhead.
