### ISSUE TITLE
Deprecated new Buffer(...) warning on NodeJS 12

### ISSUE THREAD

**Issue by hieuhlc** [evanw/node-source-map-support#242]
It's been deprecated for a while. We should fix this.

<img width="1049" alt="buffer issue" src="https://user-images.githubusercontent.com/4828178/58226064-39601f80-7d4f-11e9-8bd9-3b0d1092b600.png">

Ref: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation

**Comment by LinusU** [comment]
I don't think the warning is from this package, you're seeing that in the stack trace because of how we are hooking into `process.emit`.

We are using `buffer-from` specifically to avoid this: https://github.com/evanw/node-source-map-support/search?q=Buffer&unscoped_q=Buffer

Happy to re-open if I missed something ☺️

**Comment by kahan002** [comment]
line 149 in source-map-support.js is a deprecated use of new buffer() . It should be:sourceMapData = new Buffer.from(rawData, "base64").toString();
When I make the change, the error goes away. Please re-open and fix.
